server:
  port: 8070
grpc:
  client:
    grpc-dev:
      address: static://localhost:9000
      negotiationType: plaintext
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: profile-group
      properties:
        spring.json.trusted.packages: com.example.*

  datasource:
    url: jdbc:postgresql://localhost:5433/dbuserproject
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true

